apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test123
  annotations:
    github.com/project-slug: KalyaniNakatNineleaps/test123
spec:
  type: other
  lifecycle: unknown
  owner: KalyaniNakatNineleaps
